import { visualEffectsCatalog } from './visual-effects-assets';
export const assetCatalog: Readonly<Record<string, string>> = {
  ...visualEffectsCatalog,
  ...Object.fromEntries(
    [
      'ink-chapel-altar',
      'ink-chapel-window',
      'ink-chapel-pew',
      'ink-chapel-broken-pew',
      'ink-chapel-collapse',
      'ink-chapel-floor',
      'ink-crypt-stone',
      'ink-crypt-damp',
      'ink-crypt-marble',
      'ink-crypt',
      'ink-crypt-wall',
      'ink-crypt-flame',
      'ink-crypt-ambient',
      'ink-crypt-feature',
    ].map((id) => [id, `generated/ink/${id}/manifest.json`]),
  ),
  ...Object.fromEntries(
    [
      'ink-tended-marker',
      'ink-tended-fragments',
      'ink-tended-roots',
      'ink-tended-understory',
      'ink-tended-woodland-near',
      'ink-tended-woodland-far',
      'ink-hero-current',
      'ink-skeleton',
      'ink-scenery',
      'ink-chapel-front',
      'ink-blackwood-oak',
      'ink-blackwood-woodland',
      'ink-churchyard-roof',
      'ink-graveyard-scenery',
      'ink-graveyard-overlays',
      'ink-graveyard-materials',
      'ink-ambient',
      'ink-soil',
      'ink-moss',
      'ink-masonry',
      'ink-decals',
      'ink-ground-transitions',
      'ink-cues',
    ].map((id) => [id, `generated/ink/${id}/manifest.json`]),
  ),
};

export const gameAssetCatalog = assetCatalog;
