import type { WorldVisualDefinition } from './world-art';
export const cryptFoundation: WorldVisualDefinition = {
  surround: {
    anchor: {
      x: 0,
      z: 0,
    },
    color: 3427150,
    ground: [
      {
        x: -9,
        z: -8,
      },
      {
        x: -6,
        z: -12,
      },
      {
        x: 5,
        z: -12,
      },
      {
        x: 9,
        z: -8,
      },
      {
        x: 10,
        z: 1,
      },
      {
        x: 9,
        z: 9,
      },
      {
        x: 3,
        z: 13,
      },
      {
        x: -5,
        z: 12,
      },
      {
        x: -9,
        z: 8,
      },
      {
        x: -10,
        z: 0,
      },
    ],
    layers: [
      {
        asset: 'ink-tended-woodland-far',
        clip: 'woodland-far',
        scale: 1.7,
        base: -2,
        parallax: 0.65,
        tint: 6321017,
        detail: 0.06,
      },
      {
        asset: 'ink-tended-woodland-far',
        clip: 'woodland-far',
        scale: 2,
        base: -4,
        parallax: 0.85,
        tint: 4085072,
        detail: 0.15,
      },
    ],
  },
  floor: 'ink-chapel-floor',
  interior: {
    minX: -6,
    maxX: 6,
    minZ: -9,
    maxZ: 9,
  },
  props: [
    {
      id: 'crypt-return-door',
      clip: 'doorway',
      asset: 'ink-crypt',
      x: 0,
      z: 9,
      door: true,
      shadow: 'none',
      tint: 14737104,
      purpose: 'Registered return door seated at the retained safe threshold',
    },
    {
      id: 'crypt-glass',
      clip: 'window',
      asset: 'ink-chapel-window',
      x: 0,
      z: -8.795,
      y: 0.8,
      wallFace: 'crypt-rear',
      shadow: 'none',
      purpose: 'Damaged lancet window depicting a surviving lantern bearer',
    },
    {
      id: 'crypt-mural',
      clip: 'mural',
      asset: 'ink-crypt-wall',
      x: -5.795,
      z: -5.25,
      y: 1.25,
      scale: 0.38,
      wallFace: 'crypt-west',
      shadow: 'none',
      tint: 13028292,
      purpose: 'Single faded devotional fragment above the west prayer table',
    },
  ],
  walls: [
    {
      id: 'crypt-west',
      from: {
        x: -6,
        z: 9,
      },
      to: {
        x: -6,
        z: -9,
      },
      height: 3.6,
      thickness: 0.38,
      surface: 'masonry',
    },
    {
      id: 'crypt-rear',
      from: {
        x: -6,
        z: -9,
      },
      to: {
        x: 6,
        z: -9,
      },
      height: 4.2,
      thickness: 0.38,
      surface: 'masonry',
    },
    {
      id: 'crypt-front-0',
      from: {
        x: -6,
        z: 9,
      },
      to: {
        x: -1.2,
        z: 9,
      },
      height: 0.65,
      thickness: 0.38,
      surface: 'masonry',
      assembly: 'crypt-entry-0',
      fade: true,
    },
    {
      id: 'crypt-front-1',
      from: {
        x: 1.2,
        z: 9,
      },
      to: {
        x: 6,
        z: 9,
      },
      height: 0.65,
      thickness: 0.38,
      surface: 'masonry',
      assembly: 'crypt-entry-1',
      fade: true,
    },
    {
      id: 'crypt-east-0',
      from: {
        x: 6,
        z: 9,
      },
      to: {
        x: 6,
        z: 2,
      },
      height: 0.65,
      thickness: 0.38,
      surface: 'masonry',
      assembly: 'crypt-east-bay-0',
      fade: true,
    },
    {
      id: 'crypt-east-1',
      from: {
        x: 6,
        z: 2,
      },
      to: {
        x: 6,
        z: -2.2,
      },
      height: 0.26,
      thickness: 0.38,
      surface: 'masonry',
      assembly: 'crypt-east-bay-1',
      fade: true,
    },
    {
      id: 'crypt-east-2',
      from: {
        x: 6,
        z: -2.2,
      },
      to: {
        x: 6,
        z: -9,
      },
      height: 0.65,
      thickness: 0.38,
      surface: 'masonry',
      assembly: 'crypt-east-bay-2',
      fade: true,
    },
  ],
  assemblies: [
    {
      id: 'crypt',
      origin: {
        x: 0,
        z: 0,
      },
      props: [
        {
          id: 'crypt-return-door',
          clip: 'doorway',
          asset: 'ink-crypt',
          x: 0,
          z: 9,
          door: true,
          shadow: 'none',
          tint: 14737104,
          purpose: 'Registered return door seated at the retained safe threshold',
        },
        {
          id: 'crypt-glass',
          clip: 'window',
          asset: 'ink-chapel-window',
          x: 0,
          z: -8.795,
          y: 0.8,
          wallFace: 'crypt-rear',
          shadow: 'none',
          purpose: 'Damaged lancet window depicting a surviving lantern bearer',
        },
        {
          id: 'crypt-mural',
          clip: 'mural',
          asset: 'ink-crypt-wall',
          x: -5.795,
          z: -5.25,
          y: 1.25,
          scale: 0.38,
          wallFace: 'crypt-west',
          shadow: 'none',
          tint: 13028292,
          purpose: 'Single faded devotional fragment above the west prayer table',
        },
      ],
      walls: [
        {
          id: 'crypt-west',
          from: {
            x: -6,
            z: 9,
          },
          to: {
            x: -6,
            z: -9,
          },
          height: 3.6,
          thickness: 0.38,
          surface: 'masonry',
        },
        {
          id: 'crypt-rear',
          from: {
            x: -6,
            z: -9,
          },
          to: {
            x: 6,
            z: -9,
          },
          height: 4.2,
          thickness: 0.38,
          surface: 'masonry',
        },
        {
          id: 'crypt-front-0',
          from: {
            x: -6,
            z: 9,
          },
          to: {
            x: -1.2,
            z: 9,
          },
          height: 0.65,
          thickness: 0.38,
          surface: 'masonry',
          assembly: 'crypt-entry-0',
          fade: true,
        },
        {
          id: 'crypt-front-1',
          from: {
            x: 1.2,
            z: 9,
          },
          to: {
            x: 6,
            z: 9,
          },
          height: 0.65,
          thickness: 0.38,
          surface: 'masonry',
          assembly: 'crypt-entry-1',
          fade: true,
        },
        {
          id: 'crypt-east-0',
          from: {
            x: 6,
            z: 9,
          },
          to: {
            x: 6,
            z: 2,
          },
          height: 0.65,
          thickness: 0.38,
          surface: 'masonry',
          assembly: 'crypt-east-bay-0',
          fade: true,
        },
        {
          id: 'crypt-east-1',
          from: {
            x: 6,
            z: 2,
          },
          to: {
            x: 6,
            z: -2.2,
          },
          height: 0.26,
          thickness: 0.38,
          surface: 'masonry',
          assembly: 'crypt-east-bay-1',
          fade: true,
        },
        {
          id: 'crypt-east-2',
          from: {
            x: 6,
            z: -2.2,
          },
          to: {
            x: 6,
            z: -9,
          },
          height: 0.65,
          thickness: 0.38,
          surface: 'masonry',
          assembly: 'crypt-east-bay-2',
          fade: true,
        },
      ],
    },
  ],
  paths: [],
  graves: [],
  patches: [],
  lights: [],
  proceduralAssets: [
    'ink-moss',
    'ink-crypt-flame',
    'ink-masonry',
    'ink-cues',
    'ink-crypt-ambient',
    'ink-crypt-feature',
  ],
  decals: [],
  camera: {
    bounds: {
      minX: -2,
      maxX: 2,
      minZ: -6,
      maxZ: 5.9,
    },
    bias: {
      x: 0,
      z: -1.5,
    },
    targetHeight: 0.6,
    arrival: {
      start: 3,
      end: 7.5,
      biasZ: -7,
      span: 11,
      targetHeight: 2.2,
    },
  },
  propOrder: [
    'chapel-woodland-0',
    'chapel-woodland-1',
    'chapel-woodland-2',
    'chapel-woodland-3',
    'chapel-woodland-4',
    'crypt-pier-0-0',
    'crypt-pier-0-1',
    'crypt-pier-0-2',
    'crypt-pier-0-3',
    'crypt-pier-1-0',
    'crypt-pier-1-1',
    'crypt-pier-1-2',
    'crypt-pier-1-3',
    'crypt-return-door',
    'chapel-pew-0-0',
    'chapel-pew-0-1',
    'chapel-pew-1-0',
    'chapel-pew-1-1',
    'crypt-altar',
    'crypt-sanctuary-pier-0',
    'crypt-sanctuary-pier-1',
    'crypt-glass',
    'crypt-altar-candles',
    'chapel-devotional-table',
    'chapel-devotional-candles',
    'crypt-mural',
    'crypt-tomb',
    'chapel-collapse',
    'crypt-entry-lamp',
  ],
};
