import { assetFilterHTML } from '../assets/asset-browser';
export const assetPickerUI = `<input id="asset-search" type="search" placeholder="Search assets…" aria-label="Search assets"><details data-section="asset-filters"><summary>Asset filters</summary>${assetFilterHTML('asset-type')}</details><label>Asset<select id="asset"></select></label><output id="asset-count"></output>`;
export const sandboxUI = `<section data-preview-panel="animation" id="lab" hidden>
<button id="return-scene">Return to scene</button>
${assetPickerUI}<label>Clip<select id="clip"></select></label><label>Direction<select id="heading"></select></label>
<label for="scrub">Timeline <span id="visual-time"></span></label><input id="scrub" type="range" min="0" max="800" value="0" step="1">
<div class="buttons"><button id="step">Step frame</button><label>Speed<select id="speed"><option value=".25">¼×</option><option value="0.5">½×</option><option value="1" selected>1×</option><option value="2">2×</option></select></label></div>
<details data-section="animation-comparison"><summary>Comparison &amp; treatment</summary><button id="walk-compare">Compare hero walk</button>
<label>Compare<select id="animation-comparison"><option value="treatment">Treatment</option><option value="timing">Timing</option></select></label><p id="walk-comparison" hidden></p>
<label>Treatment<select id="walk-blend"></select></label><p id="walk-blend-help"></p><label>Stabilization<input id="walk-stabilized" type="checkbox" checked></label><label>Rigid sword<input id="walk-rigid-sword" type="checkbox" checked></label><label>Walk timing<select id="locomotion-timing"></select></label><p id="locomotion-timing-help"></p></details>
<details data-section="animation-view"><summary>View &amp; registration</summary><label for="lab-zoom">Zoom <output id="lab-zoom-value">200%</output></label><div class="preview-zoom"><button id="lab-zoom-out" aria-label="Zoom out">−</button><input id="lab-zoom" type="range" min="50" max="400" step="1" value="200"><button id="lab-zoom-in" aria-label="Zoom in">+</button><button id="lab-zoom-reset">Reset</button></div><label>Anchors, trim &amp; sockets<input id="overlays" type="checkbox"></label><label>Backdrop<select id="background"><option value="dark">Dark</option><option value="light">Light</option></select></label></details>
<details data-section="animation-timing"><summary>Timing &amp; events</summary><div class="timeline"></div><p id="action-timing"></p><p id="frame-status"></p><output id="notify"></output></details></section>
<section data-preview-panel="visuals" id="lighting-lab" hidden>
<label>Light<select id="lighting-rig"><option value="golden">Golden hour</option><option value="silver">Silver hour</option></select></label><label>Look<select id="lighting-look"><option value="ink">Atmospheric ink</option><option value="diorama" selected>HD-2D diorama</option><option value="cinematic">Dark cinematic</option></select></label>
<label>Original rendering<input type="checkbox" id="lighting-baseline"></label><label>All effects off<input type="checkbox" id="scene-baseline"></label>
<details data-section="visuals-lighting"><summary>Lighting &amp; focus</summary><label>Lighting<input type="checkbox" id="lighting-enabled" checked></label><label>Shadows<input type="checkbox" id="lighting-shadows" checked></label><label>Atmosphere<input type="checkbox" id="lighting-atmosphere" checked></label><label>Postprocessing<input type="checkbox" id="lighting-post" checked></label><label for="lighting-strength">Light response <output id="lighting-strength-value">150%</output></label><input id="lighting-strength" type="range" min="0" max="200" step="5" value="150"><label for="lighting-dof">Depth of field <output id="lighting-dof-value">100%</output></label><input id="lighting-dof" type="range" min="0" max="100" step="5" value="100"></details>
<details data-section="visuals-effects"><summary>Individual effects</summary><div id="scene-effects"></div><p>Outline, wetness, grounding and shaft experiments use the Effects fixture.</p><button data-fixture="effects-playground">Open Effects fixture</button></details>
<details data-section="visuals-playback"><summary>Replay &amp; rendering</summary><button id="lighting-replay">Scripted lighting replay</button><button id="lighting-stop" hidden>Stop replay</button><p id="lighting-playback">Free play</p><label>Render scale<select id="render-scale"><option value="1">100%</option><option value="0.75">75%</option><option value="0.5">50%</option></select></label><output id="lighting-stats"></output></details></section>
<section data-preview-panel="inspect" hidden><label>Registration &amp; collision<input id="collision" type="checkbox"></label><label>Framing<select id="zoom-span"><option value="9">9 m</option><option value="11">11 m</option><option value="13">13 m</option><option value="15">15 m</option></select></label>
<details data-section="inspect-calibration" id="calibration"><summary>Scale &amp; calibration</summary><button id="calibration-toggle">Open reference view</button><p>45° azimuth · 35.264° elevation · XZ ground · +Y height · 1.8 m ruler.</p><label>Backdrop<select id="calibration-background"><option value="dark">Dark</option><option value="light">Light</option></select></label></details>
<details data-section="inspect-occlusion" id="occlusion"><summary>Occlusion &amp; placement</summary><label>Freeze enemies<input id="freeze-enemies" type="checkbox"></label><div class="buttons"><button id="occlude-front">In front</button><button id="occlude-back">Behind</button></div><output id="art-registration-status"></output></details></section>`;
export const previewHUD = `<section class="hud" hidden><div class="row"><span>Health</span><span id="hp"></span></div><div class="health"><span id="health-fill"></span></div><div class="row"><span id="enemy-count"></span><span id="state"></span></div></section><div class="actions" hidden><div>Sword<small>Left-click</small></div><div>Dodge<small id="dodge-status"></small></div><div>Lantern<small id="ability-status"></small></div></div>`;
