import {_electron as electron, type ElectronApplication,type Page} from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import os from 'node:os';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
import type {GameSave} from '../src/core/save';
import '../src/inspection';
import {heightAt} from '../src/content/world';
import type {Presentation} from '../src/presentation/scene';
type Stats=ReturnType<Presentation['stats']>;
type BenchmarkResult={frames:number[];stats:Stats;droppedMs:number};
const root=process.cwd(),benchmark=process.argv.includes('--benchmark'),visible=process.argv.includes('--visible');
const option=(name:string,fallback:string)=>{const index=process.argv.indexOf(name);return index>=0?process.argv[index+1]??fallback:fallback;};
const output=path.resolve(option('--output',path.join(root,'tmp',benchmark?'benchmark':'desktop-smoke')));
const executable=process.env.LANTERN_EXECUTABLE??path.join(root,process.platform==='win32'?'release/win-unpacked/Lantern Knight.exe':'release/mac-arm64/Lantern Knight.app/Contents/MacOS/Lantern Knight');
const profileRoot=path.resolve(option('--profile',path.join(output,'user-data')));
await fs.mkdir(output,{recursive:true});await fs.mkdir(profileRoot,{recursive:true});
// Only delete a fresh directory owned by this invocation, never a supplied path.
const profile=await fs.mkdtemp(path.join(profileRoot,'lantern-smoke-'));
const errors:string[]=[],checks:string[]=[],notRun=['shipping hardware performance','signing and distribution'];
let app!:ElectronApplication,page!:Page;let packageRecord:unknown;
const evaluate=<T>(code:string)=>page.evaluate(code) as Promise<T>;
async function launch(){
  app=await electron.launch({executablePath:executable,env:{...process.env,LANTERN_USER_DATA:profile,LANTERN_TEST_HIDDEN:visible?'0':'1'},timeout:30000});
  page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.waitForFunction(()=>window.foundation?.ready,{},{timeout:30000});if(visible)await page.bringToFront();await app.evaluate(({BrowserWindow},show)=>{const w=BrowserWindow.getAllWindows()[0]!;w.setContentSize(1440,1028);if(show)w.focus();},visible);
  if(!visible)assert.deepEqual(await app.evaluate(({app,BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0]!;return{visible:w.isVisible(),focused:w.isFocused(),focusable:w.isFocusable(),dock:process.platform==='darwin'?app.dock!.isVisible():false};}),{visible:false,focused:false,focusable:false,dock:false});
  await page.evaluate(()=>window.foundation.pause(false));
}
async function snapshot(name:string){await page.screenshot({path:path.join(output,`${name}.png`),scale:'css'});}
const state=()=>page.evaluate('JSON.parse(JSON.stringify(window.foundation.sim.hero))') as Promise<{x:number;z:number;health:number;state:string;cooldown:number;dodgeCooldown:number;aim:number}>;
const delay=(ms:number)=>page.waitForTimeout(ms);
try{
  await launch();
  const versions=await app.evaluate(({app})=>({versions:process.versions,packaged:app.isPackaged,platform:process.platform,arch:process.arch}));
  assert.equal(versions.packaged,true);checks.push('packaged offline protocol boot');
  if(!visible)checks.push('hidden non-focusable test window with no Dock activation');
  const identity=await app.evaluate(({app})=>JSON.parse(process.getBuiltinModule('fs')!.readFileSync(process.getBuiltinModule('path')!.join(app.getAppPath(),'dist/build-identity.json'),'utf8')));
  const packagePath=process.platform==='win32'?path.join(path.dirname(executable),'resources/app.asar'):path.join(path.dirname(executable),'../Resources/app.asar');
  packageRecord={build:identity,sha256:createHash('sha256').update(await fs.readFile(packagePath)).digest('hex'),platform:process.platform,arch:process.arch,manifestHash:await page.evaluate(()=>window.foundation.manifest.hash)};
  const graphics=await page.evaluate(()=>window.foundation.stats());assert.ok(graphics.webgl.includes('WebGL 2'),'actual WebGL2 context required');
  const metrics=await app.evaluate(({app,BrowserWindow})=>{const pid=BrowserWindow.getAllWindows()[0]!.webContents.getOSProcessId();return app.getAppMetrics().find(m=>m.pid===pid);});assert.equal(metrics?.sandboxed,true);const prefs={sandbox:metrics.sandboxed,contextIsolation:true,nodeIntegration:false};
  const isolation=await evaluate<{node:string;process:string;bridge:string[]}>('({node:typeof window.require,process:typeof window.process,bridge:Object.keys(window.lantern)})');assert.equal(isolation.node,'undefined');assert.equal(isolation.process,'undefined');assert.deepEqual(isolation.bridge.sort(),['loadGame','loadSettings','saveGame','saveSettings']);checks.push('actual sandboxed preload bridge, no Node access');
  await assert.rejects(page.evaluate(()=>window.lantern!.saveSettings({version:2,renderScale:99,showDebug:false,verticalSpan:13})));checks.push('actual IPC rejects invalid payload');
  if(benchmark){
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0]!.setContentSize(2560,1568));await delay(200);
    assert.deepEqual((await page.evaluate(()=>window.foundation.stats())).buffer,[2560,1440]);
    const runs=[];
    for(const stress of [false,true]){
      await page.evaluate(s=>window.foundation.startBenchmark(s),stress);await delay(5000);
      await page.evaluate(s=>window.foundation.startBenchmark(s),stress);await delay(stress?15000:60000);
      const result=await page.evaluate(()=>window.foundation.finishBenchmark(false));assert.ok(result.simulatedTicks>=(stress?15:60)*50,'benchmark simulation paused or stalled');await snapshot(stress?'stress-1440p':'encounter-1440p');
      const sorted=(result.frames as number[]).slice(1).sort((a,b)=>a-b),percentile=(p:number)=>sorted[Math.floor((sorted.length-1)*p)]!;
      runs.push({...result,frames:undefined,fixture:stress?'32 actors stress':'4 actors representative',samples:sorted.length,medianMs:percentile(.5),p95Ms:percentile(.95),maxMs:sorted.at(-1),over33ms:sorted.filter(v=>v>33.4).length});
    }
    await page.evaluate(()=>window.foundation.finishBenchmark());
    const lifetime=[];for(let i=0;i<8;i++){await page.evaluate(()=>window.foundation.reset());await delay(120);lifetime.push(await page.evaluate(()=>window.foundation.stats()));}
    await fs.writeFile(path.join(output,'performance.json'),JSON.stringify({date:'2026-10-06',environment:{hidden:!visible,machine:option('--machine',os.cpus()[0]?.model??'unidentified CPU'),cpuCount:os.cpus().length,ramBytes:os.totalmem(),os:os.release(),display:option('--display','physical display/refresh not specified'),window:'2560×1568 logical content; 2560×1440 drawing buffer, DPR cap 1',versions,three:'0.186.1',build:`packaged unsigned ${process.platform}/${process.arch} development-content checkpoint`,package:packageRecord,gpuTiming:visible?'unavailable; rAF intervals include presentation/display pacing':'unavailable; hidden-window rAF intervals do not certify visible display pacing'},runs,lifetime,errors},null,2));
  }else{
    await page.evaluate(()=>window.foundation.sim.actors.slice(1).forEach(a=>a.stun=10000));const before=await state();await page.keyboard.down('KeyW');await delay(600);await page.keyboard.up('KeyW');const after=await state();assert.ok(Math.hypot(after.x-before.x,after.z-before.z)>.7);checks.push('WASD moves on ground');
    assert.equal(await page.evaluate(()=>window.foundation.presentation.actors.get('player')!.sprite.mesh.position.y),0);checks.push('runtime quad foot stays on the simulation ground plane');
    const canvas=await page.locator('canvas').boundingBox();assert.ok(canvas);await page.mouse.move(canvas.x+canvas.width*.68,canvas.y+canvas.height*.5);await delay(50);assert.notEqual((await state()).aim,before.aim);checks.push('mouse ray aims on ground');
    await page.mouse.click(canvas.x+canvas.width*.68,canvas.y+canvas.height*.5);await delay(60);assert.equal((await state()).state,'attack');await delay(650);checks.push('sword action');
    await page.keyboard.down('Shift');await delay(70);await page.keyboard.up('Shift');assert.ok((await state()).dodgeCooldown>0);await delay(550);checks.push('dodge action');
    await page.mouse.click(canvas.x+canvas.width*.5,canvas.y+canvas.height*.6,{button:'right'});await delay(80);assert.ok((await state()).cooldown>0);await delay(550);checks.push('lantern action');
    await page.keyboard.press('Escape');const tick=await page.evaluate(()=>window.foundation.sim.tick);await delay(200);assert.equal(await page.evaluate(()=>window.foundation.sim.tick),tick);await page.getByRole('button',{name:'Resume',exact:true}).click();checks.push('pause/resume freezes ticks');
    if(visible){await app.evaluate(({app,BrowserWindow})=>{app.focus({steal:true});BrowserWindow.getAllWindows()[0]!.focus();});await page.waitForFunction(()=>document.hasFocus());}
    await page.keyboard.down('KeyW');await delay(50);const nativeFocus=await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0]!;const focused=w.isFocused();if(focused)w.blur();else w.emit('blur');return focused;});
    if(!nativeFocus)notRun.push(visible?'OS focus loss: automation host did not grant native window focus; Electron blur handler exercised directly':'OS focus loss: hidden test mode; run --visible to exercise native focus changes');
    await page.waitForFunction(()=>!document.querySelector<HTMLElement>('#modal')!.hidden);const blurTick=await page.evaluate(()=>window.foundation.sim.tick);await delay(150);assert.equal(await page.evaluate(()=>window.foundation.sim.tick),blurTick);await page.keyboard.up('KeyW');if(visible)await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0]!.focus());await page.getByRole('button',{name:'Resume',exact:true}).click();const stopped=await state();await delay(100);assert.ok(Math.hypot((await state()).x-stopped.x,(await state()).z-stopped.z)<.01);checks.push('Electron window blur path pauses, clears held input and resumes without catch-up');
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0]!.setContentSize(2560,1568));await delay(150);
    assert.deepEqual((await page.evaluate(()=>window.foundation.stats())).buffer,[2560,1440]);
    await page.getByRole('button',{name:'Calibration',exact:true}).click();await snapshot('calibration-16x9');
    await page.locator('#zoom-span').selectOption('11');await delay(100);assert.equal((await page.evaluate(()=>window.foundation.stats())).verticalSpan,11);await snapshot('framing-11');await page.locator('#zoom-span').selectOption('15');await delay(100);assert.equal((await page.evaluate(()=>window.foundation.stats())).verticalSpan,15);await snapshot('framing-15');await page.locator('#zoom-span').selectOption('13');checks.push('selected 13 m camera with tested 11–15 m framing headroom');
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0]!.setContentSize(1200,1028));await delay(150);await snapshot('calibration-4x3');checks.push('resize fixed vertical framing, 16:9 and 4:3 captures');
    for(const background of ['dark','light']){
      await page.locator('#calibration-background').selectOption(background);await delay(80);const screenshot=await page.screenshot({path:path.join(output,`calibration-${background}.png`),scale:'css'});
      const projected=await page.evaluate(()=>{const p=window.foundation.presentation,rect=p.canvas.getBoundingClientRect();return p.calibration.children.filter(o=>o.type==='Mesh'&&'material'in o&&'color'in (o.material as object)&&[0x808080,0xe9bc67,0x263b4a].includes((o.material as {color:{getHex():number}}).color.getHex())).map(o=>{const v=o.position.clone().project(p.camera),color=(o as unknown as {material:{color:{getHex():number}}}).material.color.getHex();return{x:Math.round(rect.left+(v.x+1)*rect.width/2),y:Math.round(rect.top+(1-v.y)*rect.height/2),rgb:[color>>16&255,color>>8&255,color&255]};});});
      const pixels=await sharp(screenshot).removeAlpha().raw().toBuffer({resolveWithObject:true});assert.equal(projected.length,3);for(const swatch of projected){const offset=(swatch.y*pixels.info.width+swatch.x)*3;for(let c=0;c<3;c++)assert.ok(Math.abs(pixels.data[offset+c]!-swatch.rgb[c]!)<=2,'sRGB reference swatch mismatch');}
    }checks.push('sRGB reference swatches agree on dark and light runtime backgrounds');
    await page.getByRole('button',{name:'Animation lab',exact:true}).click();await delay(150);assert.equal(await page.locator('#background').inputValue(),await page.evaluate(()=>window.foundation.presentation.background));await page.getByRole('button',{name:'Pause',exact:true}).click();await snapshot('animation-walk');
    await page.locator('#clip').selectOption('attack_sword_01');await delay(60);await page.locator('#scrub').evaluate((el:HTMLInputElement)=>{el.value='200';el.dispatchEvent(new Event('input',{bubbles:true}));});await snapshot('animation-attack');
    await page.locator('#background').selectOption('light');await delay(80);await snapshot('animation-light');await page.locator('#background').selectOption('dark');
    const independent=await evaluate<{a:string;b:string;sameTexture:boolean}>('({a:window.foundation.presentation.labSprite.lastFrame,b:window.foundation.presentation.secondSprite.lastFrame,sameTexture:window.foundation.presentation.labSprite.material.map===window.foundation.presentation.secondSprite.material.map})');assert.notEqual(independent.a,independent.b);checks.push('runtime lab exact proxy export and independent frames');
    await page.getByRole('button',{name:'Occlusion',exact:true}).click();await page.getByRole('button',{name:'Behind',exact:true}).click();await delay(120);await snapshot('occlusion-debug');await page.locator('#collision').uncheck();await page.getByRole('button',{name:'Calibration',exact:true}).click();await page.getByRole('button',{name:'Occlusion',exact:true}).click();assert.equal(await page.evaluate(()=>window.foundation.presentation.debug),false);assert.equal(await page.locator('#calibration-background').inputValue(),'dark');checks.push('inspection controls retain overlay choices and show the shared backdrop correctly');await page.getByRole('button',{name:'In front',exact:true}).click();await delay(100);await snapshot('occlusion-normal');
    for(const fixture of [{name:'actor-crossing',x:0,z:0,other:true},{name:'tree',x:2.2,z:-2.4,other:false},{name:'wall-corner',x:-3.5,z:-3.5,other:false},{name:'foreground',x:2.9,z:3.1,other:false}]){
      await page.evaluate(f=>{const s=window.foundation.sim;Object.assign(s.hero,{x:f.x,z:f.z,px:f.x,pz:f.z});if(f.other)Object.assign(s.actors[1]!,{x:.4,z:.4,px:.4,pz:.4});},fixture);await delay(100);await snapshot(`occlusion-${fixture.name}`);
    }
    for(const [x,z] of [[-7,-7],[7,7],[-7,7],[7,-7]]){
      await page.evaluate(point=>{const h=window.foundation.sim.hero;Object.assign(h,{x:point.x,z:point.z,px:point.x,pz:point.z});},{x:x!,z:z!});await delay(80);
      assert.equal(await page.evaluate(()=>{const p=window.foundation.presentation,m=p.actors.get('player')!.sprite.mesh,vertices=m.geometry.getAttribute('position');for(let i=0;i<vertices.count;i++){const v=m.position.clone().fromBufferAttribute(vertices,i).applyMatrix4(m.matrixWorld).project(p.camera);if(Math.abs(v.x)>1||Math.abs(v.y)>1)return false;}return true;}),true);
    }checks.push('translation-only follow keeps full hero sprite visible at all room corners');
    await page.getByRole('button',{name:'Encounter',exact:true}).click();await page.evaluate(()=>window.foundation.reset());
    await page.evaluate(()=>window.foundation.sim.actors.slice(1).forEach(a=>a.stun=10000));
    const attackPoint=await page.locator('canvas').boundingBox();assert.ok(attackPoint);
    await page.mouse.click(attackPoint.x+attackPoint.width*.65,attackPoint.y+attackPoint.height*.55);
    await page.waitForFunction(()=>window.foundation.sim.hero.state==='attack'&&window.foundation.sim.hero.age>=17);
    await page.mouse.click(attackPoint.x+attackPoint.width*.65,attackPoint.y+attackPoint.height*.55);
    await page.waitForFunction(()=>window.foundation.sim.hero.swingStage===1&&window.foundation.sim.hero.age>=15);
    await page.mouse.click(attackPoint.x+attackPoint.width*.65,attackPoint.y+attackPoint.height*.55);
    await page.waitForFunction(()=>window.foundation.sim.hero.swingStage===2&&window.foundation.sim.hero.state==='attack');checks.push('three combo stages through actual buffered mouse input');await snapshot('combo-stage-3');
    await page.evaluate(()=>window.foundation.reset());const beforeDeath=await page.evaluate(()=>window.foundation.sim.generation),beforeResetCount=await page.evaluate(()=>window.foundation.session.resetCount);
    await page.evaluate(()=>{const s=window.foundation.sim;s.damage(s.actors[1]!,s.hero,1000);});await delay(100);assert.equal((await state()).state,'death');await delay(540);
    const deathFrame=await page.evaluate(()=>{const f=window.foundation,v=f.presentation.actors.get('player')!;return{actual:v.sprite.lastFrame,expected:f.manifest.asset.clips.death![v.heading]!.frames.at(-1)};});assert.equal(deathFrame.actual,deathFrame.expected);
    await page.waitForFunction(g=>window.foundation.sim.generation>g,beforeDeath);assert.equal((await state()).health,100);assert.equal(await page.evaluate(()=>window.foundation.session.resetCount),beforeResetCount+1);checks.push('final death pose followed by exactly-once simulation room reset');
    await page.evaluate(()=>{const s=window.foundation.sim;for(const enemy of s.actors.slice(1))s.damage(s.hero,enemy,1000);});await delay(100);assert.equal(await page.evaluate(()=>window.foundation.sim.cleared),true);
    const wins=await page.evaluate(()=>window.foundation.saveValue().wins);assert.equal(wins,1);await page.getByRole('button',{name:'Pause / save',exact:true}).click();for(let i=0;i<2;i++){await page.getByRole('button',{name:'Save checkpoint',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent==='Checkpoint saved');}assert.equal(await page.evaluate(()=>window.foundation.saveValue().wins),wins);checks.push('clear progression is counted once across repeated saves');await page.getByRole('button',{name:'Resume',exact:true}).click();
    await page.evaluate(()=>{const s=window.foundation.sim;Object.assign(s.hero,{x:0,z:-6.4,px:0,pz:-6.4});});await page.keyboard.down('KeyW');await page.waitForFunction(()=>window.foundation.sim.area==='upper-landing');await page.keyboard.up('KeyW');await snapshot('linked-upper-landing');checks.push('connected area transition through the unlocked gate');
    await page.evaluate(()=>{const s=window.foundation.sim;Object.assign(s.hero,{x:0,z:-1,px:0,pz:-1});s.move(s.hero,0,0);s.actors.slice(1).forEach(a=>a.stun=10000);window.foundation.presentation.debug=true;});await delay(120);
    const support=await page.evaluate(()=>{const p=window.foundation.presentation,h=window.foundation.sim.hero,v=p.actors.get('player')!;return{hero:h.y,sprite:v.sprite.mesh.position.y,shadow:v.shadow.position.y,area:window.foundation.sim.area};});assert.equal(support.area,'upper-landing');assert.ok(Math.abs(support.hero-.225)<.001);assert.ok(Math.abs(support.sprite-support.hero)<.001);assert.ok(Math.abs(support.shadow-support.hero-.03)<.001);await snapshot('height-change-debug');checks.push('shared raised-ground query registers movement, sprite and shadow');
    await page.getByRole('button',{name:'Pause / save',exact:true}).click();await page.getByRole('button',{name:'Save checkpoint',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent==='Checkpoint saved');const saved=await page.evaluate(()=>window.foundation.saveValue());
    const savedBytes=await fs.readFile(path.join(profile,'saves/game.json'));await app.close();await launch();assert.equal(await page.evaluate(()=>window.foundation.persistence.mode),'protected');await page.evaluate(()=>{const s=window.foundation.sim;s.damage(s.enemies[0]!,s.hero,1000);s.hero.age=45;});await page.waitForFunction(()=>window.foundation.session.resetCount===1);await delay(120);assert.deepEqual(await fs.readFile(path.join(profile,'saves/game.json')),savedBytes);checks.push('startup protects existing save from a death-boundary autosave');await page.getByRole('button',{name:'Pause / save',exact:true}).click();await page.getByRole('button',{name:'Save checkpoint',exact:true}).isDisabled().then(disabled=>assert.equal(disabled,true));await page.getByRole('button',{name:'Load checkpoint',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent==='Checkpoint loaded');await page.evaluate(()=>window.foundation.pause(true));const loaded=await page.evaluate(()=>window.foundation.saveValue());assert.equal(loaded.area,saved.area);assert.equal(loaded.wins,saved.wins);assert.equal(loaded.player.health,saved.player.health);assert.ok(Math.hypot(loaded.player.x-saved.player.x,loaded.player.z-saved.player.z)<.05);checks.push('save, exit, relaunch and explicit load through actual Electron bridge');
    await page.getByRole('button',{name:'Resume',exact:true}).click();await page.evaluate(()=>{const s=window.foundation.sim;s.enemies.forEach(a=>s.damage(s.hero,a,10000));});await page.waitForFunction(()=>window.foundation.sim.cleared);await page.evaluate(()=>{const h=window.foundation.sim.hero;Object.assign(h,{x:0,z:6.4,px:0,pz:6.4,cooldown:120,dodgeCooldown:30});});await page.keyboard.down('KeyS');await page.waitForFunction(()=>window.foundation.sim.area==='court');await page.keyboard.up('KeyS');assert.ok(await page.evaluate(()=>window.foundation.sim.cleared&&window.foundation.sim.enemies.every(a=>a.health===0)));assert.ok((await state()).cooldown>80);assert.ok((await state()).dodgeCooldown>0);checks.push('actual revisit preserves cleared enemies and player cooldowns');
    await page.getByRole('button',{name:'Pause / save',exact:true}).click();const protectedBytes=await fs.readFile(path.join(profile,'saves/game.json'));await page.getByRole('button',{name:'New Game',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.deepEqual(await fs.readFile(path.join(profile,'saves/game.json')),protectedBytes);await page.getByRole('button',{name:'New Game',exact:true}).click();await page.getByRole('button',{name:'Confirm New Game',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#status')?.textContent==='New game saved');const newSave=JSON.parse(await fs.readFile(path.join(profile,'saves/game.json'),'utf8')) as GameSave;assert.equal(newSave.area,'court');assert.equal(newSave.wins,0);assert.equal(newSave.player.cooldown,0);assert.equal(Object.keys(newSave.areas).length,1);checks.push('New Game cancellation preserves save; confirmation writes a fresh baseline');
    assert.ok(await page.evaluate(()=>window.foundation.eventHistory.some(e=>e.kind==='animation-notify')));checks.push('actual runtime animation notifications reach presentation consumers');
    await page.evaluate(()=>window.foundation.fixture('systems-fixture'));await delay(100);const fixture=await page.evaluate(()=>({count:window.foundation.sim.enemies.length,health:window.foundation.sim.enemies.map(a=>a.health),foot:window.foundation.presentation.actors.get('player')!.sprite.mesh.position.y,hero:window.foundation.sim.hero.y}));assert.equal(fixture.count,5);assert.ok(fixture.health.includes(140));assert.equal(fixture.foot,fixture.hero);assert.equal((await state()).health,100);await snapshot('systems-fixture');checks.push('packaged third area renders five independently configured melee actors');
    await page.getByRole('button',{name:'Animation lab',exact:true}).click();await page.evaluate(()=>{const p=window.foundation.presentation,source=p.packs.get('placeholder')!,manifest=structuredClone(source.manifest);manifest.asset.id='diagnostic-registration-fixture';manifest.asset.canvas=[448,512];manifest.asset.anchor=[224,412];manifest.asset.density=144;manifest.frames.forEach(f=>{f.trim[0]+=32;f.trim[1]+=64;for(const point of Object.values(f.attachments)){point[0]+=32;point[1]+=64;}});p.packs.set('registration-fixture',{manifest,textures:source.textures,release:source.release});p.selectLabAsset('registration-fixture');const assets=document.querySelector<HTMLSelectElement>('#asset')!;assets.add(new Option('Synthetic registration fixture','registration-fixture'));assets.value='registration-fixture';document.querySelector<HTMLSelectElement>('#clip')!.value=p.labClip;});await delay(100);const registration=await page.evaluate(()=>{const p=window.foundation.presentation;return{canvas:p.labSprite.manifest.asset.canvas,density:p.labSprite.manifest.asset.density,otherDensity:p.secondSprite.manifest.asset.density,sameTexture:p.labSprite.material.map===p.secondSprite.material.map};});assert.deepEqual(registration.canvas,[448,512]);assert.equal(registration.density,144);assert.equal(registration.otherDensity,192);await snapshot('independent-registration');await page.evaluate(()=>{const p=window.foundation.presentation;p.selectLabAsset('placeholder');p.packs.delete('registration-fixture');const assets=document.querySelector<HTMLSelectElement>('#asset')!;assets.querySelector('option[value="registration-fixture"]')!.remove();assets.value='placeholder';document.querySelector<HTMLSelectElement>('#clip')!.value=p.labClip;});await page.getByRole('button',{name:'Encounter',exact:true}).click();checks.push('actual lab isolates synthetic registration metadata while reusing unchanged atlas pixels');

    const lifetime=[];for(let i=0;i<8;i++){await page.evaluate(()=>window.foundation.reset());await delay(100);lifetime.push(await page.evaluate(()=>window.foundation.stats()));}assert.equal(lifetime.at(-1)!.objects.geometries,lifetime[2]!.objects.geometries);assert.equal(lifetime.at(-1)!.objects.textures,lifetime[2]!.objects.textures);checks.push('8 room replacement cycles: stable GPU object counts');
    const replacement=await page.evaluate(async()=>{const before=window.foundation.sim.generation,outcomes=await Promise.allSettled([window.foundation.reset(),window.foundation.reset()]);return{before,after:window.foundation.sim.generation,statuses:outcomes.map(v=>v.status)};});assert.equal(replacement.after,replacement.before+1);assert.deepEqual(replacement.statuses,['rejected','fulfilled']);checks.push('interrupted room load suppressed with exactly one committed replacement');
    const settingsFile=path.join(profile,'saves/settings.json'),priorSettings=await fs.readFile(settingsFile),unsupportedSettings=JSON.stringify({version:99});
    await app.close();await fs.writeFile(settingsFile,unsupportedSettings);await launch();
    await page.waitForFunction(()=>document.querySelector('#status')!.textContent!.startsWith('Settings unavailable:'));
    await page.evaluate(()=>window.foundation.pause(true));assert.match(await page.locator('#save-notice').innerText(),/Settings unavailable:/);
    await page.getByRole('button',{name:'Load checkpoint',exact:true}).click();await page.waitForFunction(()=>window.foundation.persistence.canWrite);await page.evaluate(()=>window.foundation.pause(true));
    await page.getByRole('button',{name:'Save checkpoint',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#save-notice')!.textContent!.includes('Newer save version'));
    assert.equal(await fs.readFile(settingsFile,'utf8'),unsupportedSettings);await fs.writeFile(settingsFile,priorSettings);
    await page.getByRole('button',{name:'Save checkpoint',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#status')!.textContent==='Checkpoint saved');
    assert.ok(!(await page.locator('#save-notice').innerText()).includes('Settings unavailable:'));checks.push('unreadable settings stay visible and preserved; a successful settings save clears the error');
    if(!visible)assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0]!.isVisible()),false);
    await fs.writeFile(path.join(output,'desktop-smoke.json'),JSON.stringify({hidden:!visible,package:packageRecord,graphics:await page.evaluate(()=>window.foundation.stats()),notRun,versions,prefs:{sandbox:prefs.sandbox,contextIsolation:prefs.contextIsolation,nodeIntegration:prefs.nodeIntegration},checks,independent,lifetime,errors},null,2));
  }
  assert.deepEqual(errors,[]);await fs.rm(path.join(output,'desktop-failure.txt'),{force:true});console.log(`PASS: ${checks.length} desktop checks; ${benchmark?'benchmark':'smoke'} evidence saved.`);
}catch(error){console.error(error);if(page){await snapshot('failure').catch(()=>{});}await fs.writeFile(path.join(output,'failure.json'),JSON.stringify({package:packageRecord,checks,errors,error:String(error),notRun:['remaining checks after failure']},null,2));await fs.writeFile(path.join(output,'desktop-failure.txt'),String(error)+'\n'+errors.join('\n'));process.exitCode=1;}
finally{if(app)await app.close();await fs.rm(profile,{recursive:true,force:true});}
